Fix compilation on older systems
When compiling on CentOS 7 (GCC 4.8, Glibc 2.17) there were numerous
build failures.

1) C99 loop initial declarations used

src/config.c: In function ‘ff_parse_arguments’:
src/config.c:31:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int i = 1; i < argc; i++)
     ^
src/config.c:31:5: note: use option -std=c99 or -std=gnu99 to compile your code

   GCC 4.8 defaults[0] to gnu90 (C90 + GNU extensions)

   ff-proxy doesn't seem to be using any GNU extensions so just compile
   with -std=c99.

2) strcasecmp(3) technically requires strings.h, glibc does declare this
   in string.h depending on what feature test macros are defined. But
   lets just include strings.h in src/config.c

3) getaddrinfo(3)/freeaddrinfo(3) requires sys/types.h in src/server.c,
   also the following item

4) A lot of errors relating to not knowing about struct addrinfo and
   various AI_ flags. The simplest thing to do here is to just define
   _GNU_SOURCE at compilation time.

5) The server needs to link against -lm for ceil(3)

[0]: https://gcc.gnu.org/onlinedocs/gcc-4.8.0/gcc/Standards.html