http: Allow to skip hostname validation for OpenSSL < 1.0.2
When compiling with OpenSSL prior to 1.0.2 the following errors are
produced

src/http.c:280:5: warning: implicit declaration of function 'SSL_get0_param' [-Wimplicit-function-declaration]
...
src/http.c:281:5: warning: implicit declaration of function 'X509_VERIFY_PARAM_set1_host' [-Wimplicit-function-declaration]

These functions were only added in OpenSSL 1.0.2

Doing hostname validation prior to OpenSSL 1.0.2 is somewhat
convoluted[0], for this use case it's perhaps better to allow it to be
skipped when using OpenSSL older than 1.0.2

Add a check in the Makefile for the OpenSSL version and halt the build
and print a message saying what to do in such cases. E.g

    $ make
    ***
    *** OpenSSL too old (< 1.0.2)
    ***
    *** If you are OK with skipping hostname validation then please build with
    ***
    *** make OPENSSL_SKIP_HOST_VALIDATION=1
    ***
    make: *** [Makefile:39: build_check] Error 1

this way the user is fully aware of what is happening...

[0]: https://wiki.openssl.org/index.php/Hostname_validation